학습계획작성 및 미션1 구현
codesquad-members-2023/swift-photoframe pull request #10
Opened 2023-03-06 07:46 UTC by dpfdlalfm

- 학습 계획 체크리스트 작성
- 미션 1 구현 및 리드미에 정리

2023-03-06 08:06 UTC, godrm requested changes
리드미에 업무용 체크리스트와 학습용 체크리스트틀 좀 더 보완해보세요.
PR 열어놓은 채로 커밋 + 푸시하시고 완료되면 댓글을 남겨주세요

2023-03-06 08:06 UTC, godrm commented on PhotoFrame/PhotoFrame/SceneDelegate.swift
> +        // to restore the scene back to its current state.
프로젝트를 만들면서 생기는 AppDelegate나 SceneDelegate 파일처럼 자동으로 생기는 파일도 본인의 의도를 표현해야 합니다  
여기 파일은 전혀 건드리면 안되는게 아니라, 의미가 없거나 구현할 필요가 없으면 지워도 됩니다  
특히 이런 주석은 프로젝트를 만들고 나서 안내해주는 것인데, 이 프로젝트를 구현하는 데 필요가 없으면 지워주세요

2023-03-06 08:06 UTC, godrm commented on PhotoFrame/PhotoFrame/ViewController.swift
> +        // Do any additional setup after loading the view.
Step1-1을 했다고 했는데 탭바 컨트롤러가 없거나 뷰 컨트롤러가 두 개가 아닌 것 같은데요? 확인해주세요

2023-03-06 08:06 UTC, godrm commented on PhotoFrame/PhotoFrameUITests/PhotoFrameUITests.swift
> +    }
테스트 코드가 포함되어 있네요. 프로젝트를 만들 때도 사용하지 않는 것은 스스로 관리할 수 있어야 합니다
무조건 그냥 만드는 게 아니라, 이게 어떤 의미가 있고, 왜 사용하는 거고, 언제 사용하는건지 판단이 들어야 프로젝트에 포함하는 거죠
지금처럼 프로젝트 템플릿으로 생성되는 옵션을 켜두는 게 항상 좋은게 아닙니다. 왜냐하면 여기 코드가 전혀 없기 때문이죠

2023-03-06 08:06 UTC, godrm commented on README.md
> +2. View Controller 2개 연결
학습 계획을 세우는 것은 크게 2가지 단계까 있습니다
- 요구사항에 맞춰서 무엇을 구현할 것인가 스스로 확인하고
- 무엇을 구현할 것인가를 작은 단위 업무용 체크리스트로 만들어 봐야 합니다
- 그렇게 만든 체크리스트는 커밋하는 단위가 될 수 있습니다. 예를 들어 탭바 컨트롤러를 추가하는 게 하나의 커밋 = 체크리스트, 탭바컨트롤러에 뷰 컨트롤러를 연결하고 커스텀 클래스를 지정하는 게 또 다른 커밋 = 체크리스트. 이런 식이 될 수 있습니다. 
- 그리고 우리는 학습중이라서 학습을 위한 체크리스트도 만들어보시면 좋겠습니다

2023-03-07 01:43 UTC, godrm commented
새로 올린 커밋들이 모두 수정된건가요? 
완료되고 나면 댓글을 꼭 남겨주셔야 완료된지 알 수 있습니다.

2023-03-07 01:52 UTC, dpfdlalfm commented
말씀해주신 부분 반영해서 수정하여 커밋하였습니다!
댓글 바로 남기는걸 깜빡했네요 앞으로는 바로 하도록 하겠습니다

2023-03-07 02:15 UTC, godrm commented on PhotoFrame/PhotoFrame/AppDelegate.swift
>  import UIKit
파일 윗 부분에 남는 주석은 어떤 의미나 목적이 있을까요?
코드에 대한 정보를 주는 주석은 좋은 주석입니다. 이 파일이 어떤 목적이 있고, 누가 작성했는지 남겨놓는 의미도 있습니다. 참고하세요

2023-03-07 02:16 UTC, godrm commented on README.md
> +2. View Controller 2개 연결
어제보다 더 상세하게 잘 나누셨네요. 처음에 일주일 정도 분량을 모두 다 정리하기 어려울 수 있습니다
하루-이틀 정도 상세하게 나누고 나머지는 이후에 추가해도 좋습니다. 참고하세요

2023-03-07 02:17 UTC, godrm commented on PhotoFrame/PhotoFrame/FirstScene.swift
> +    @IBOutlet weak var photoLabel: UILabel!
var photoLabel 과 func viewDidLoad 는 FirstScene에서 어떤 역할일까요?
func와 var를 파일에 선언하는 위치도 개발자의 의도를 표현하는 부분입니다. 어떤 것을 위에서 아래로 쓰는 게 좋을까요? 머지하더라도 댓글을 남겨봐주세요

2023-03-07 02:17 UTC, godrm approved these changes

2023-03-07 02:18 UTC, merged

2023-03-07 04:49 UTC, dpfdlalfm commented on PhotoFrame/PhotoFrame/FirstScene.swift
> +    @IBOutlet weak var photoLabel: UILabel!
- photoLabel은 1-2 스텝 미션을 진행해서 있는거 같습니다 😂
- viewDidLoad()의 경우 새로운 ViewController를 선언할 경우 필수적으로 선언해야되는 부분인 줄 알고 작성했지만,
  (실제로는 선언 안해줘도 상관 없다는 것을 알게 되었습니다. -> 차후 README에 작성 예정)
- 변수는 최상단에 오도록 하는게 가독성이 좋을 것 같습니다