Sol
codesquad-members-2023/swift-photoframe pull request #3
Opened 2023-03-06 07:02 UTC by HansolWorld

1. README.md 변경
- 학습계획 추가
- 기능구현 리스트 추가
2. 프로젝트 폴더 추가

2023-03-06 07:05 UTC, godrm requested changes

2023-03-06 07:05 UTC, godrm commented on README.md
> +7. 이미지 추가기능 구현
기능 요구사항을 루카스에 스텝보다 더 작은 단위로 나눠보는 걸 추천합니다
예를 들러 TabBarController를 추가하려면 ViewController도 2개를 작업해야 할텐데, 탭별로 하나씩 추가하는 게 하나의 작업이라고 나눌 수 있습니다.

2023-03-06 07:05 UTC, godrm commented on PhotoFrame/PhotoFrame/PhotoFrameApp.swift
> +}
어.. SwiftUI 프로젝트네요. 우선 UIKit 프로젝트를 먼저 살펴볼 예정입니다. 
프로젝트 지우고 다시 생성해야 할 수도 있겠네요

2023-03-06 07:07 UTC, HansolWorld commented on README.md
> +7. 이미지 추가기능 구현
그럼 기능단위로 스텝을 최대한 나누는 연습을 하겠습니다!

2023-03-06 07:15 UTC, godrm commented on README.md
> +7. 이미지 추가기능 구현
그렇게 작게 나눈 작업 단위가 커밋하는 단위가 될 수 있을 겁니다.

2023-03-06 07:16 UTC, godrm commented on PhotoFrame/PhotoFrame/ViewController.swift
> +        // Do any additional setup after loading the view.
프로젝트 생성 Step1-1 요구사항이 탭바 컨트롤러와 뷰 컨트롤러 확인하는 게 있지 않던가요? 확인해봐주세요!

2023-03-06 07:34 UTC, HansolWorld commented on PhotoFrame/PhotoFrame/ViewController.swift
> +        // Do any additional setup after loading the view.
아! "1. 프로젝트 생성하기"가 1-1이 되는거군요! 이해했습니다! 수정하겠습니다!

2023-03-07 01:42 UTC, godrm commented
수정하고 커밋-푸시가 마무리된건가요? 완료됐으면 댓글 남겨주세요

2023-03-07 03:40 UTC, HansolWorld commented
@godrm step1_1 마무리 했습니다.

2023-03-07 03:46 UTC, merged