Harimrim
codesquad-members-2023/swift-photoframe pull request #7
Opened 2023-03-06 07:30 UTC by harimrim

프로젝트 생성 및 학습 계획 작성

2023-03-06 08:14 UTC, godrm requested changes
다음 내용을 확인해보고 주석 부분 수정하고, 리드미도 수정해서 다시 커밋하고 푸시해보세요
모두 완료되면 노티를 위해서 댓글을 꼭 남겨주세요

2023-03-06 08:14 UTC, godrm commented on .gitignore
> +iOSInjectionProject/
`.gitignore` 파일을 추가했네요. 이건 왜 추가했나요? 어떤 의도가 있나요?

2023-03-06 08:14 UTC, godrm commented on PhotoFrame/PhotoFrame/AppDelegate.swift
> +        // Use this method to release any resources that were specific to the discarded scenes, as they will not return.
프로젝트를 만들면서 생기는 AppDelegate나 SceneDelegate 파일처럼 자동으로 생기는 파일도 본인의 의도를 표현해야 합니다  
여기 파일은 전혀 건드리면 안되는게 아니라, 의미가 없거나 구현할 필요가 없으면 지워도 됩니다  
특히 이런 주석은 프로젝트를 만들고 나서 안내해주는 것인데, 이 프로젝트를 구현하는 데 필요가 없으면 지워주세요

2023-03-06 08:14 UTC, godrm commented on PhotoFrame/PhotoFrame/ViewController.swift
> +        print(#file, #line, #function, #column)
viewDidLoad는 어떤 메소드인가요? 왜 여기에 print를 하면 값이 찍히나요?

2023-03-06 08:14 UTC, godrm commented on README.md
> +델리게이트랑 프로토콜
이렇게 쓴걸 보면 일주일 분량을 모두 학습하고 정리한 느낌적인 느낌이네요. 
이건 학습 정리인지, 할 일을 위한 체크리스트인지, 구현해야 하는 목록인지 구분이 안됩니다

우선 기능요구사항 + 프로그래밍 요구사항을 분석해보고, 구현해야 하는 업무용 체크리스트를 루카스에 있는 스텝보다 더 작은 단위로 나눠보세요. 예를 들어 탭바 컨트롤러를 추가하는 게 하나의 커밋 = 체크리스트, 탭바컨트롤러에 뷰 컨트롤러를 연결하고 커스텀 클래스를 지정하는 게 또 다른 커밋 = 체크리스트. 이런 식이 될 수 있습니다.

그리고 그렇게 구현해야 하는 업무들 중에 학습할 게 있으면 따로 학습을 위한 체크리스트를 두면 어떨까요? 
물론 세부적으로 다음 단계로 넘어가기 전에 모든 단계에서 필요한 것을 미리 알고 계획하기는 어렵습니다
그러니까 앞의 단계는 좀 더 구체적으로 계획하고, 뒷 단계는 좀 덜 하게 작성할 수도 있겠죠

2023-03-07 03:29 UTC, godrm commented
언급한 내용에 대해 수정해서 커밋 + 푸시까지 완료된 건가요? 
완료되면 꼭 댓글로 남겨주셔야 끝난 줄 알 수 있습니다.

2023-03-07 08:52 UTC, harimrim commented on PhotoFrame/PhotoFrame/ViewController.swift
> +        print(#file, #line, #function, #column)
UIViewController에 선언되어 있는 메소드로 View가 메모리에 올라가면서 한번 호출되면서 print 값이 찍히게 됩니다

2023-03-07 08:52 UTC, harimrim commented on .gitignore
> +iOSInjectionProject/
xcuserdata 처럼 User setting 같이 레포지토리에 올라갈 필요가 없는 파일들을 구분하기 위해 추가했습니다!

2023-03-08 01:01 UTC, harimrim commented
언급하신 내용에 대한 수정해서 커밋 + 푸시 완료하였습니다!

2023-03-08 03:03 UTC, godrm approved these changes

2023-03-08 03:03 UTC, merged